import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/app/components/ui/theme-provider";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "./components/ui/toaster";

export const metadata: Metadata = {
  title: "Vandana Singh & Associates",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/images/4.png",
      href: "/images/4.png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
